### ISSUE TITLE
How did horizontal achieve this?

### ISSUE THREAD

**Issue by ETmanwenhan** [JoniVR/VerticalCardSwiper#12]
How did horizontal achieve this?

**Comment by JoniVR** [comment]
Hi @ETmanwenhan 

I'm not sure what you're asking? Could you please elaborate on what you mean exactly?

**If you mean if it's possible to have horizontal scrolling cards instead of vertical:**
That's currently not supported and I don't think it will be in the future since it would require a lot of rewriting and would make the code very messy. 

There was an issue about this earlier #10 in which I went into some detail and provided a partial implementation on how to do this, I suggest you take a look at that. 

**If you mean how did I achieve the swiping of the cards to the side then I suggest you take a look at the following files:**
* [VerticalCardSwiper.swift](
https://github.com/JoniVR/VerticalCardSwiper/blob/master/Sources/VerticalCardSwiper.swift) (look at the `handlePan` function)
* [CardCell.swift
](https://github.com/JoniVR/VerticalCardSwiper/blob/master/Sources/CardCell.swift)

These files contain the most important logic for the side swiping.

Hope this helps.

Best regards
Joni

**Comment by ETmanwenhan** [comment]
![28d246c9-b25d-4820-8ee9-506a7d1af438](https://user-images.githubusercontent.com/5837888/45541008-6e22eb00-b840-11e8-8ba9-cac5a4774494.png)
I want to achieve the effect of horizontal scrolling!

**Comment by JoniVR** [comment]
Alright, then I suggest you either look at issue #10, as I've already talked a lot about this over there.

Or, alternatively, I would suggest something like this:
https://github.com/fahidattique55/FAPaginationLayout

Hope this helps 🙂
