### ISSUE TITLE
Shazam effect

### ISSUE THREAD

**Issue by VladIacobIonut** [JoniVR/VerticalCardSwiper#13]
I cloned the project in the attempt to include the stack effect for the vertical collection as in Shazam. I managed to do so except the fact that sometimes the stack displays two cards behind, sometimes three. Did you came across this problem when trying to implement this effect ? I think the problem is the third cell (which should be displayed in the background always when the indexPath is greater or equal to 2) sometimes gets deallocated, sometimes it doesn't. Do you have any guess on this ?

Thank you.

**Comment by VladIacobIonut** [comment]
I opened a PR (#14) for that as well so you can see the implementation

**Comment by JoniVR** [comment]
Hi @VladIacobIonut 

First of all, thanks for contributing.

I haven't properly looked into adding the effect before because I was trying to get things as stable as possible, but it's really great that you've already started looking into it. 
It could indeed be something you describe, as I've seen some indexPath and zPosition issues before.
I'm currently a bit limited in free time, but I'll try to look at it in the next few hours. Thanks again!

Kind regards
Joni

**Comment by JoniVR** [comment]
You are correct, for some reason this only seems to be happening on index 5 and 9 on the example code. I'll try to figure out what's happening but I'm currently not sure.

**Comment by VladIacobIonut** [comment]
Indeed, didn't notice however this always happens on indexes 5 and 9 but it's true. Please let me know if you fix it. I will also be looking for a fix in the meanwhile.

Thank you,
Vlad.

**Comment by JoniVR** [comment]
I did some more debugging and figured out the following things (nothing special really, just some extra info on the bug):

* The issue already existed before your implementation of the stack effect.
* It is indeed a cell reuse issue (on certain indexes 5,9 for example it will have 4 instead of 3 "visible cells")

I thought I might be because some layout differences because of the cell scaling or something (some cells being a little bit smaller causing the system to adjust the amount of visible cells), but after comparing in the debugger, the cell sizes seem to be the same on both, here's the comparison:

<img width="550" alt="info 3 cells - index 4" src="https://user-images.githubusercontent.com/7591717/46699934-9fae8c80-cc1b-11e8-9b0e-1c749c03f590.png">
<img width="550" alt="info 4 cells - index 5" src="https://user-images.githubusercontent.com/7591717/46699937-a1785000-cc1b-11e8-8ef4-fa31a24c7a34.png">

So that doesn't seem to be the issue at first sight. Will look further into this whenever I get some time but I'm extremely time constrained right now so it'll probably take some time for me to figure it out.

**Comment by VladIacobIonut** [comment]
Sure. I am even considering the case in which Shazam uses two static views behind the CollectionView to simulate the stack effect. But I really hope I'm wrong. 

Thank you anyways for looking into this !

**Comment by JoniVR** [comment]
They could possibly just be using UIViews too, I've seen it before, but the reason I picked `UICollectionview` as a base layer to start from was the cell reuse so.. hope I'm not going to regret that decision lol

**Comment by JoniVR** [comment]
Opened a Stackoverflow question on this:
https://stackoverflow.com/questions/52739405/uicollectionview-custom-layout-some-indexes-have-more-visible-cells-than-others

I'll edit this comment whenever I find new observations and post them below.
Here are some observations:
* The issue already existed before your implementation of the stack effect.
* It is indeed a cell reuse issue (on certain indexes 5,9 for example it will have 4 instead of 3 "visible cells").
* It happens every 4-5 cards where it shows a stack of 3 cards instead of 2.

**Comment by VladIacobIonut** [comment]
Good !! I'll keep an eye on it myself

**Comment by JoniVR** [comment]
I submitted the fix someone suggested on stackoverflow, as far as I can tell there still a little issue where the card position isn't 100% right after starting a swipe to either side and then aborting, but this should be fairly easy to fix.

**Comment by VladIacobIonut** [comment]
Hi again,

I'm happy to hear this got fixed somehow! as I hope I'll use this one day in a real app. I watched the thread on Stackoverflow as well but didn't notice a new answer was posted until this morning when you replied here. I only noticed that guy who implied the problem might come from the collectionviewlayout which decides to show only two cards. Fairly this was my intuition as well, but I didn't dare to modify it and simply extend UICollectionViewLayout 😅.  

Thank you for helping 👍

**Comment by JoniVR** [comment]
I submitted a fix for the final glitch and everything seems to be working now, I'll merge this into a separate branch and then into development. After that I'll push development to master when I release the next version (which should be pretty soon).

**edit:**
Almost forgot! thanks for contributing by the way 🙂 I mentioned you in the [Changelog](https://github.com/JoniVR/VerticalCardSwiper/blob/master/CHANGELOG.md).
