### ISSUE TITLE
Switching Orientation

### ISSUE THREAD

**Issue by mightymango** [JoniVR/VerticalCardSwiper#16]
When switching between portrait and landscape the layout does not update. If however I remove a card by swiping left or right, it then updates.

Is there a way to force this layout update on orientation change?

**Comment by JoniVR** [comment]
Hi @mightymango 

Rotating views isn't really something I've looked into thus far, so landscape isn't tested or supported in any way currently.

However, it should work with some minor adjustments.
I haven't tried this yet, but you should be able to manually force the layout to redraw (even though it should do that by itself already). 

Try doing something like (inside your `UIViewController`):
```swift
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {

    // this forces the layout to be redrawn
    cardSwiper.verticalCardSwiperView!.collectionViewLayout.invalidateLayout()
}
```

Let me know if works or not, otherwise I'll look into this later since I'm currently a bit busy.

Kind regards
Joni

**Comment by mightymango** [comment]
Thanks for the very quick response 😊

You just beat me to it, I was just trying the same solution:

```
override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
    super.viewWillTransition(to: size, with: coordinator)

    if UIDevice.current.orientation.isLandscape,
        let layout = cardSwiper.verticalCardSwiperView.collectionViewLayout as? UICollectionViewFlowLayout {
        //Add code here to fine tune layout

        //Force layout to redraw
        layout.invalidateLayout()
    } else if UIDevice.current.orientation.isPortrait,
        let layout = cardSwiper.verticalCardSwiperView.collectionViewLayout as? UICollectionViewFlowLayout {
        //Add code here to fine tune layout

        //Force layout to redraw
        layout.invalidateLayout()
    }

}

```

The above allows for changing spacing etc. for different orientations.
