### ISSUE TITLE
UITapGestureRecognizer in card not working

### ISSUE THREAD

**Issue by darnfish** [JoniVR/VerticalCardSwiper#18]
I’m trying to add a UITapGestureRecognizer to one of the cards in order to present a modal when the card is tapped, but the recognizer isn’t working.

It works fine when VerticalCardSwiper isn’t being used.

**Comment by JoniVR** [comment]
Hi @williamsthing 

Are you trying to detect a tap anywhere inside a card or for something specific? 
The `VerticalCardSwiper` internally makes use of different gestureRecognizers te detect horizontal and vertical swipes and also uses `shouldRecognizeSimultaneouslyWith`, this could possibly interfere with other gesture recognisers, but I'll have to look inside the code to test that. 

If you're looking for a tap anywhere inside a card, I can look into adding a delegate method for that and pushing it in an extra release since it's a pretty useful thing that should've already been included anyways.

Could you perhaps share how/where you are trying to add the extra recogniser? Might help me out in figuring out what's going wrong exactly. 🙂 

Kind regards
Joni

**Comment by darnfish** [comment]
Hi Joni,

Thanks for the quick response. I have a UIView inside of the card item that is setup to listen to gesture recognisers. Also is it possible to remove the horizontal swipe gesture recogniser when `isSideSwipingEnabled` is set to false? I have the VerticalCardSwiper in a CollectionView (horizontal) that has paging, and the swipes are ignored by the CollectionView when the gesture takes place on top of the VeritcalCardSwiper, if that makes sense.

Having a look at the source now and trying to fix it, I'll make a pull request if I have any success. Thanks!!

**Comment by darnfish** [comment]
Opened a pull request: https://github.com/JoniVR/VerticalCardSwiper/pull/19
