### ISSUE TITLE
Calling `scrollToCard` before the `VerticalCardSwiper` is fully initialized causes a nil crash

### ISSUE THREAD

**Issue by bugaco** [JoniVR/VerticalCardSwiper#37]
### New Issue Checklist

- [x] I read the [Contribution Guidelines](CONTRIBUTING.md).
- [x] I read the [documentation](https://github.com/JoniVR/VerticalCardSwiper).
- [x] I updated VerticalCardSwiper to the latest version.
- [x] I searched for [existing GitHub issues](https://github.com/JoniVR/VerticalCardSwiper/issues).

### Issue Description
Xcode crashed occasionally:
![image](https://user-images.githubusercontent.com/23650458/54890795-e5b78e00-4ee5-11e9-9912-368fcb62d2af.png)
 

### Environment

- **iOS Version**: 12.1
- **Device(s)**: iPhone X Simulator
- **Xcode Version**: 10.1

**Comment by JoniVR** [comment]
Hi @zanyzephyr 

Could you please tell me in which function you call the `scrollToCard` function?
Do you call it at the beginning?

Would be useful if you could provide some of your code where you call it.
Thanks for the screenshot, always helps.

Kind regards
Joni

**Comment by bugaco** [comment]
Hi,thank you for replying.
Yeah, I call the `scrollToCard` at the beginning.

But when I do that after a little delay , It works well.
![image](https://user-images.githubusercontent.com/23650458/54972043-96945a80-4fc4-11e9-874e-4b015e11aa9e.png)

**Comment by JoniVR** [comment]
Hi,

I would recommend not using a delay since that might not always work (depending on how long the device takes to load te code).

The reason why it's crashing is probably because it's being called before the `VerticalCardSwiper` is properly set up (this is one of the annoying limitations of `UICollectionView` but I think I should be able to fix it). 
The documentation for `scrollToCard` tells you that if you want to call this function from the start, you should do it inside `viewDidLayoutSubviews`.

It still shouldn't give you a crash, and that is my mistake, which I will look into fixing, but I would not recommend using a delay.

Kind regards,
Joni

**Comment by JoniVR** [comment]
Just letting you know that version 1.0.0 has been released which fixes this issue 😉

**Comment by bugaco** [comment]
> Just letting you know that version 1.0.0 has been released which fixes this issue 😉

Yeah, I update it to 1.0.0,  and remove the `0.2 delay`, now it works well👍🏿
