### ISSUE TITLE
Unexpectedly found nil while unwrapping an Optional Value

### ISSUE THREAD

**Issue by lurein** [JoniVR/VerticalCardSwiper#8]
After following the steps outlined in the readme, I get the following error in viewDidLoad on the line: cardSwiper.datasource = self

Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value
causing the app to crash on startup.

**Comment by JoniVR** [comment]
Hi @lurein 

After testing with a new project, it seems like you're right, I'm getting the same problem.

I'll look into it and try to release a fixed version today. 

Thank you for letting me know.

**Comment by JoniVR** [comment]
@lurein If you want a workaround right now and don't mind using storyboard, try adding the VerticalCardSwiper class to the view of the controller (or take a look at the example), that approach still seems to work.

![schermafbeelding 2018-06-29 om 13 54 19](https://user-images.githubusercontent.com/7591717/42091088-30629f64-7ba4-11e8-9b59-4b367ae6c8c6.png)

**Comment by JoniVR** [comment]
Forgot to reference this issue, but it should be fixed in b4642a0 by changing up the example code and using the `init(frame: CGRect)` function instead. I think something just went wrong with casting the view.

I'll release it in a moment so you can use this method.

Closing this issue, feel free to reopen if you still come across it.

**edit:** version `0.1.0-beta3` is released, which should fix the issue (better method in README)
